namespace: dev
resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/T1kcan/vote
    newTag: dev-023fb1e57fcc28d4c963d687b81d03ed133efe9f
  - name: ghcr.io/T1kcan/result
    newTag: dev-023fb1e57fcc28d4c963d687b81d03ed133efe9f
