namespace: dev
resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/T1kcan/vote
    newTag: dev-fc3bb58a6602661db3091f74926c2a4395f059db
  - name: ghcr.io/T1kcan/result
    newTag: dev-fc3bb58a6602661db3091f74926c2a4395f059db
