name: CI - Voting App Dev

on:
  push:
    branches:
      - master
      - dev

jobs:
  push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Images
        run: |
          docker build -t ghcr.io/t1kcan/vote:dev-${COMMIT_SHA} ./vote
          docker push ghcr.io/t1kcan/vote:dev-${COMMIT_SHA}

          docker build -t ghcr.io/t1kcan/result:dev-${COMMIT_SHA} ./result
          docker push ghcr.io/t1kcan/result:dev-${COMMIT_SHA}

      - name: Update Kustomize image tags
        run: |
          sed -i "s|newTag:.*|newTag: dev-${COMMIT_SHA}|" k8s/overlays/dev/kustomization.yaml

      - name: Commit & Push changes
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add k8s/overlays/dev/kustomization.yaml
          git commit -m "Update dev image tags to ${COMMIT_SHA}"
          git push
