name: CI - Voting App Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - master

jobs:
  sast:
    name: Static Code Analysis (CodeQL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
                
  push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Images
        run: |
          docker build -t ghcr.io/t1kcan/vote:dev-${COMMIT_SHA} ./vote
          docker push ghcr.io/t1kcan/vote:dev-${COMMIT_SHA}

          docker build -t ghcr.io/t1kcan/result:dev-${COMMIT_SHA} ./result
          docker push ghcr.io/t1kcan/result:dev-${COMMIT_SHA}

      - name: Set ENV_NAME from branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Update kustomization.yaml image tags
        run: |
          sed -i "s|newTag:.*|newTag: ${ENV_NAME}-${COMMIT_SHA}|" k8s/overlays/${ENV_NAME}/kustomization.yaml

      - name: Commit updated kustomization.yaml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/overlays/${ENV_NAME}/kustomization.yaml
          git commit -m "Update image tag to ${ENV_NAME}-${COMMIT_SHA}"
          git push